// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class CloudKitBackupError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "CloudKitBackupError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? CloudKitBackupError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Mirrors CKAccountStatus.
enum IcloudAccountStatus: Int {
  case available = 0
  case noAccount = 1
  case restricted = 2
  case couldNotDetermine = 3
  case temporarilyUnavailable = 4
}

/// Metadata stored alongside the single backup record.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BackupMetadata {
  /// Record modification time, epoch milliseconds.
  var updatedAtEpochMs: Int64
  var deviceName: String
  var deckCount: Int64
  var cardCount: Int64
  var version: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BackupMetadata? {
    let updatedAtEpochMs = pigeonVar_list[0] as! Int64
    let deviceName = pigeonVar_list[1] as! String
    let deckCount = pigeonVar_list[2] as! Int64
    let cardCount = pigeonVar_list[3] as! Int64
    let version = pigeonVar_list[4] as! String

    return BackupMetadata(
      updatedAtEpochMs: updatedAtEpochMs,
      deviceName: deviceName,
      deckCount: deckCount,
      cardCount: cardCount,
      version: version
    )
  }
  func toList() -> [Any?] {
    return [
      updatedAtEpochMs,
      deviceName,
      deckCount,
      cardCount,
      version,
    ]
  }
}

private class CloudKitBackupApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return IcloudAccountStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return BackupMetadata.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CloudKitBackupApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? IcloudAccountStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BackupMetadata {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CloudKitBackupApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CloudKitBackupApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CloudKitBackupApiPigeonCodecWriter(data: data)
  }
}

class CloudKitBackupApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CloudKitBackupApiPigeonCodec(readerWriter: CloudKitBackupApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CloudKitBackupApi {
  /// Current iCloud account status for the app's CloudKit container.
  func accountStatus(completion: @escaping (Result<IcloudAccountStatus, Error>) -> Void)
  /// Overwrites the single backup record with [jsonPayload] (stored as a
  /// CKAsset) plus metadata fields.
  func saveBackup(jsonPayload: String, deckCount: Int64, cardCount: Int64, version: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Metadata of the backup record, or null if none exists.
  func fetchBackupMetadata(completion: @escaping (Result<BackupMetadata?, Error>) -> Void)
  /// The JSON payload of the backup record, or null if none exists.
  func fetchBackupPayload(completion: @escaping (Result<String?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CloudKitBackupApiSetup {
  static var codec: FlutterStandardMessageCodec { CloudKitBackupApiPigeonCodec.shared }
  /// Sets up an instance of `CloudKitBackupApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CloudKitBackupApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Current iCloud account status for the app's CloudKit container.
    let accountStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poc_ai_quiz.CloudKitBackupApi.accountStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      accountStatusChannel.setMessageHandler { _, reply in
        api.accountStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      accountStatusChannel.setMessageHandler(nil)
    }
    /// Overwrites the single backup record with [jsonPayload] (stored as a
    /// CKAsset) plus metadata fields.
    let saveBackupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poc_ai_quiz.CloudKitBackupApi.saveBackup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveBackupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jsonPayloadArg = args[0] as! String
        let deckCountArg = args[1] as! Int64
        let cardCountArg = args[2] as! Int64
        let versionArg = args[3] as! String
        api.saveBackup(jsonPayload: jsonPayloadArg, deckCount: deckCountArg, cardCount: cardCountArg, version: versionArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveBackupChannel.setMessageHandler(nil)
    }
    /// Metadata of the backup record, or null if none exists.
    let fetchBackupMetadataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poc_ai_quiz.CloudKitBackupApi.fetchBackupMetadata\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchBackupMetadataChannel.setMessageHandler { _, reply in
        api.fetchBackupMetadata { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchBackupMetadataChannel.setMessageHandler(nil)
    }
    /// The JSON payload of the backup record, or null if none exists.
    let fetchBackupPayloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poc_ai_quiz.CloudKitBackupApi.fetchBackupPayload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchBackupPayloadChannel.setMessageHandler { _, reply in
        api.fetchBackupPayload { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchBackupPayloadChannel.setMessageHandler(nil)
    }
  }
}
