// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct CardAnswerResult {
  /// How correct the answer is, from 0.0 to 1.0
  var howCorrect: Double
  /// AI reasoning for the score
  var reasoning: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CardAnswerResult? {
    let howCorrect = pigeonVar_list[0] as! Double
    let reasoning = pigeonVar_list[1] as! String

    return CardAnswerResult(
      howCorrect: howCorrect,
      reasoning: reasoning
    )
  }
  func toList() -> [Any?] {
    return [
      howCorrect,
      reasoning,
    ]
  }
}

private class OnDeviceAiApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CardAnswerResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class OnDeviceAiApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CardAnswerResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class OnDeviceAiApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return OnDeviceAiApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return OnDeviceAiApiPigeonCodecWriter(data: data)
  }
}

class OnDeviceAiApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = OnDeviceAiApiPigeonCodec(readerWriter: OnDeviceAiApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OnDeviceAiApi {
  /// Check if on-device AI is available on this platform
  func isOnDeviceAIAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Validate a user's answer against the correct answer using on-device AI
  func validateAnswer(userAnswer: String, correctAnswer: String, completion: @escaping (Result<CardAnswerResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OnDeviceAiApiSetup {
  static var codec: FlutterStandardMessageCodec { OnDeviceAiApiPigeonCodec.shared }
  
  /// Convenience method to set up the API with the Foundation Models implementation
  static func setUpWithFoundationModels(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    let implementation = OnDeviceAiApiImplementation()
    setUp(binaryMessenger: binaryMessenger, api: implementation, messageChannelSuffix: messageChannelSuffix)
  }
  /// Sets up an instance of `OnDeviceAiApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OnDeviceAiApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Check if on-device AI is available on this platform
    let isOnDeviceAIAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poc_ai_quiz.OnDeviceAiApi.isOnDeviceAIAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isOnDeviceAIAvailableChannel.setMessageHandler { _, reply in
        api.isOnDeviceAIAvailable { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isOnDeviceAIAvailableChannel.setMessageHandler(nil)
    }
    /// Validate a user's answer against the correct answer using on-device AI
    let validateAnswerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poc_ai_quiz.OnDeviceAiApi.validateAnswer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateAnswerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userAnswerArg = args[0] as! String
        let correctAnswerArg = args[1] as! String
        api.validateAnswer(userAnswer: userAnswerArg, correctAnswer: correctAnswerArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      validateAnswerChannel.setMessageHandler(nil)
    }
  }
}
