// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI5VFgJDZ8jDQve17iJkc1zAebKb2psXA',
    appId: '1:897552655477:android:39ac6517281f560443043c',
    messagingSenderId: '897552655477',
    projectId: 'quizzy-ai-85865',
    storageBucket: 'quizzy-ai-85865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6F0d_poQUW_1WSjI9J6eR7k1VSis7KE',
    appId: '1:897552655477:ios:67f1aa77aa7ec77343043c',
    messagingSenderId: '897552655477',
    projectId: 'quizzy-ai-85865',
    storageBucket: 'quizzy-ai-85865.firebasestorage.app',
    iosBundleId: 'com.chechoora.quizzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ6F0d_poQUW_1WSjI9J6eR7k1VSis7KE',
    appId: '1:897552655477:ios:3f0e5e322b1935ce43043c',
    messagingSenderId: '897552655477',
    projectId: 'quizzy-ai-85865',
    storageBucket: 'quizzy-ai-85865.firebasestorage.app',
    iosBundleId: 'com.example.pocAiQuiz',
  );
}
