// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.chechoora.poc_ai_quiz

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class CardAnswerResult (
  /** How correct the answer is, from 0.0 to 1.0 */
  val howCorrect: Double,
  /** AI reasoning for the score */
  val reasoning: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CardAnswerResult {
      val howCorrect = pigeonVar_list[0] as Double
      val reasoning = pigeonVar_list[1] as String
      return CardAnswerResult(howCorrect, reasoning)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      howCorrect,
      reasoning,
    )
  }
}
private open class OnDeviceAiApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CardAnswerResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CardAnswerResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OnDeviceAiApi {
  /** Check if on-device AI is available on this platform */
  fun isOnDeviceAIAvailable(callback: (Result<Boolean>) -> Unit)
  /** Validate a user's answer against the correct answer using on-device AI */
  fun validateAnswer(userAnswer: String, correctAnswer: String, callback: (Result<CardAnswerResult>) -> Unit)

  companion object {
    /** The codec used by OnDeviceAiApi. */
    val codec: MessageCodec<Any?> by lazy {
      OnDeviceAiApiPigeonCodec()
    }
    /** Sets up an instance of `OnDeviceAiApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OnDeviceAiApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poc_ai_quiz.OnDeviceAiApi.isOnDeviceAIAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isOnDeviceAIAvailable{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poc_ai_quiz.OnDeviceAiApi.validateAnswer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val userAnswerArg = args[0] as String
            val correctAnswerArg = args[1] as String
            api.validateAnswer(userAnswerArg, correctAnswerArg) { result: Result<CardAnswerResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
